---
name: Net-RTorrent
version: 0.03
author:
  - 'Zahatski Aliaksandr, E<lt>zag@cpan.orgE<gt>'
abstract: Perl interface to rtorrent via XML-RPC.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Collection: 0.02
  RPC::XML: 0.63
provides:
  Net::RTorrent:
    file: lib/Net/RTorrent.pm
    version: 0.03
  Net::RTorrent::DItem:
    file: lib/Net/RTorrent/DItem.pm
    version: 0.01
  Net::RTorrent::Downloads:
    file: lib/Net/RTorrent/Downloads.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
