---
name: Net-RTorrent
version: 0.08
author:
  - 'Zahatski Aliaksandr, E<lt>zag@cpan.orgE<gt>'
abstract: Perl interface to rtorrent via XML-RPC.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Collection: 0.43
  RPC::XML: 0.63
configure_requires:
  Module::Build: 0.35
provides:
  Net::RTorrent:
    file: lib/Net/RTorrent.pm
    version: 0.08
  Net::RTorrent::DItem:
    file: lib/Net/RTorrent/DItem.pm
    version: 0.01
  Net::RTorrent::Downloads:
    file: lib/Net/RTorrent/Downloads.pm
    version: 0.01
  Net::RTorrent::Socket:
    file: lib/Net/RTorrent/Socket.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
